version: '2'

services:  
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/hnginternship.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network
  php:
    image: php:7-fpm
    volumes:
      - ./src:/src
      - ./php/logging.conf:/usr/local/etc/php-fpm.d/zzlast-log.conf
    networks:
      - web-network
networks:
  web-network:
    driver: bridge